# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask yaml2 psycopg2
        sudo apt-get --yes install python3-psycopg2 curl
        sudo apt-get --yes install apt-transport-https ca-certificates curl software-properties-common
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
        sudo apt-get --yes install docker-ce
    - name: Run unittest
      run: |
        python test_show_result.py
    - name: Build
      run: |
        docker build -f dockerfile -t errbx/epam_task03:latest .
        docker login -u errbx --password-stdin "Vfhnvfhn123" docker.com
        docker push errbx/epam_task03:latest
